/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dropwizard.ms;

import com.dropwizard.ms.api.UserDetailsResource;
import com.dropwizard.ms.api.WelcomeResource;
import com.dropwizard.ms.metrics.HealthCheckMetric;
import io.dropwizard.Application;
import io.dropwizard.jersey.protobuf.ProtocolBufferMessageBodyProvider;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;

public class App extends Application<AppConfiguration> {
    public static void main(String[] args) throws Exception {
        new App().run(args);
    }

    @Override
    public String getName() {
        return "app";
    }

    @Override
    public void initialize(Bootstrap<AppConfiguration> bootstrap) {
        // nothing to do yet
    }

    @Override
    public void run(AppConfiguration configuration, Environment environment) {
        final UserDetailsResource resource = new UserDetailsResource(configuration.getTemplate(),
                configuration.getDefaultName());
        final WelcomeResource welcomeResource = new WelcomeResource();
        final HealthCheckMetric healthCheckMetric = new HealthCheckMetric(configuration.getTemplate());
        environment.healthChecks().register("template",healthCheckMetric);
        environment.jersey().register(resource);
        environment.jersey().register(welcomeResource);
        environment.jersey().register(ProtocolBufferMessageBodyProvider.class);

    }

}