/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dropwizard.ms;

import com.dropwizard.ms.api.UserDetailsResource;
import io.dropwizard.Application;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;

public class App extends Application<AppConfiguration> {
    public static void main(String[] args) throws Exception {
        new App().run(args);
    }

    @Override
    public String getName() {
        return "app";
    }

    @Override
    public void initialize(Bootstrap<AppConfiguration> bootstrap) {
        // nothing to do yet
    }

    @Override
    public void run(AppConfiguration configuration, Environment environment) {
        final UserDetailsResource resource = new UserDetailsResource(configuration.getTemplate(),
                configuration.getDefaultName());
        environment.jersey().register(resource);
    }

}